version: 5.0.5-{build}

before_build:
  - nuget restore
  
branches:
  except:
    - gh-pages
    - data
    
skip_tags: true

image: Visual Studio 2015

build:
  parallel: true
  project: Trifolia.sln
  
test:
  assemblies:
    - Trifolia.Test.dll
